/*
* BANCO CRIADO COM CARINHO POR IGHOR DRUMMOND.
* DATA: 29/08/2024
* OBJETIVO: CRIAR BANCO, TABELA E DADOS PADRÕES.
*/  

# CRIANDO BANCO DE DADOS
CREATE DATABASE DB_SECTOTECA CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

# USANDO O BANCO
USE DB_SECTOTECA;

# CRIANDO TABELAS 
/*
TABELA: USERS
DESCRIÇÃO: RESPONSÁVEL POR ARMAZENAR OS USUÁRIOS
DATA: 29/08/2024
PROGRAMADOR(A): IGHOR DRUMMOND
*/
CREATE TABLE USERS(
    id_user INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name_user VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    status_user BOOLEAN DEFAULT TRUE,
    birth_date TIMESTAMP NOT NULL,
    email varchar(100)  NOT NULL,
    password_user VARCHAR(255) NOT NULL -- Criptografia Hash SHA-256
);

/*
TABELA: PLAYLIST_BOOK
DESCRIÇÃO: RESPONSÁVEL POR CRIAR A PLAYLIST DE EBOOKS
DATA: 29/08/2024
PROGRAMADOR(A): IGHOR DRUMMOND
*/
CREATE TABLE PLAYLIST_BOOK(
    id_playlist INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR(100) NOT NULL DEFAULT '',
    descriptions VARCHAR(200) DEFAULT 'Não há descrição para este livro',
    author VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id_user INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES USERS(id_user)
);

/*
TABELA: CONTENT
DESCRIÇÃO: RESPONSÁVEL POR ARMAZENAR OS CONTÉUDOS DA PLAYLIST
DATA: 29/08/2024
PROGRAMADOR(A): IGHOR DRUMMOND
*/
CREATE TABLE CONTENT(
    id_content INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    id_playlist INT NOT NULL,
    title VARCHAR(100) NOT NULL DEFAULT '',
    author VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_playlist) REFERENCES PLAYLIST_BOOK(id_playlist)
);